/** Large pools — random subset is chosen per session for variety. */
export const questionBank = {
  Easy: [
    {
      bankId: 'e-t1',
      difficulty: 'Easy',
      type: 'text',
      prompt: 'What is the difference between a Python list and a tuple?',
      expectedKeywords: ['mutable', 'immutable'],
    },
    {
      bankId: 'e-t2',
      difficulty: 'Easy',
      type: 'text',
      prompt: 'What does `if __name__ == "__main__"` mean in Python?',
      expectedKeywords: ['script', 'module', 'run'],
    },
    {
      bankId: 'e-t3',
      difficulty: 'Easy',
      type: 'text',
      prompt: 'What is indentation used for in Python?',
      expectedKeywords: ['block', 'scope', 'syntax'],
    },
    {
      bankId: 'e-t4',
      difficulty: 'Easy',
      type: 'text',
      prompt: 'What is a virtual environment and why use it?',
      expectedKeywords: ['dependencies', 'isolate', 'packages'],
    },
    {
      bankId: 'e-c1',
      difficulty: 'Easy',
      type: 'code',
      prompt: 'Write `def sum_n(n)` that returns the sum of the first n natural numbers (1+2+...+n).',
      starterCode: 'def sum_n(n):\n    pass',
      codeEvaluator: 'sum_natural',
      expectedOutput: '15',
    },
    {
      bankId: 'e-c2',
      difficulty: 'Easy',
      type: 'code',
      prompt: 'Write `def is_even(x)` that returns True if x is an even integer.',
      starterCode: 'def is_even(x):\n    pass',
      codeEvaluator: 'is_even',
      expectedOutput: 'true',
    },
    {
      bankId: 'e-c3',
      difficulty: 'Easy',
      type: 'code',
      prompt: 'Write `def rev(s)` that returns the reversed string of `s`.',
      starterCode: 'def rev(s):\n    pass',
      codeEvaluator: 'reverse_string',
      expectedOutput: 'cba',
    },
  ],
  Medium: [
    {
      bankId: 'm-t1',
      difficulty: 'Medium',
      type: 'text',
      prompt: 'Explain time complexity of binary search on a sorted array.',
      expectedKeywords: ['log', 'sorted', 'half'],
    },
    {
      bankId: 'm-t2',
      difficulty: 'Medium',
      type: 'text',
      prompt: 'What is the difference between `==` and `is` in Python?',
      expectedKeywords: ['value', 'identity', 'object'],
    },
    {
      bankId: 'm-t3',
      difficulty: 'Medium',
      type: 'text',
      prompt: 'What is a decorator in Python?',
      expectedKeywords: ['function', 'wrap', 'modify'],
    },
    {
      bankId: 'm-t4',
      difficulty: 'Medium',
      type: 'text',
      prompt: 'Explain Big-O notation in one sentence.',
      expectedKeywords: ['growth', 'upper', 'bound'],
    },
    {
      bankId: 'm-c1',
      difficulty: 'Medium',
      type: 'code',
      prompt: 'Write `def fact(n)` that returns n! (factorial) for n ≥ 0.',
      starterCode: 'def fact(n):\n    pass',
      codeEvaluator: 'factorial',
      expectedOutput: '120',
    },
    {
      bankId: 'm-c2',
      difficulty: 'Medium',
      type: 'code',
      prompt: 'Write `def max_in_list(nums)` that returns the maximum number in list `nums`.',
      starterCode: 'def max_in_list(nums):\n    pass',
      codeEvaluator: 'max_in_list',
      expectedOutput: '9',
    },
    {
      bankId: 'm-c3',
      difficulty: 'Medium',
      type: 'code',
      prompt: 'Write `def count_vowels(s)` that counts vowels (a,e,i,o,u) in string `s` (case insensitive).',
      starterCode: 'def count_vowels(s):\n    pass',
      codeEvaluator: 'count_vowels',
      expectedOutput: '3',
    },
  ],
  Hard: [
    {
      bankId: 'h-t0',
      difficulty: 'Hard',
      type: 'text',
      prompt: 'What is the CAP theorem? Name the three trade-offs.',
      expectedKeywords: ['consistency', 'availability', 'partition'],
    },
    {
      bankId: 'h-t1',
      difficulty: 'Hard',
      type: 'text',
      prompt: 'Compare BFS vs DFS for graph traversal. When would you prefer each?',
      expectedKeywords: ['queue', 'stack', 'shortest', 'depth'],
    },
    {
      bankId: 'h-t2',
      difficulty: 'Hard',
      type: 'text',
      prompt: 'What is dynamic programming? Give a one-line intuition.',
      expectedKeywords: ['overlap', 'subproblem', 'optimal'],
    },
    {
      bankId: 'h-t3',
      difficulty: 'Hard',
      type: 'text',
      prompt: 'Explain ACID properties in databases.',
      expectedKeywords: ['atomic', 'consistent', 'isolated', 'durable'],
    },
    {
      bankId: 'h-c1',
      difficulty: 'Hard',
      type: 'code',
      prompt: 'Write `def fib(n)` that returns the nth Fibonacci number (0-indexed: fib(0)=0, fib(1)=1).',
      starterCode: 'def fib(n):\n    pass',
      codeEvaluator: 'fibonacci',
      expectedOutput: '8',
    },
    {
      bankId: 'h-c2',
      difficulty: 'Hard',
      type: 'code',
      prompt: 'Write `def binary_search(arr, x)` returning index of `x` in sorted `arr` or -1.',
      starterCode: 'def binary_search(arr, x):\n    pass',
      codeEvaluator: 'binary_search',
      expectedOutput: '2',
    },
    {
      bankId: 'h-c3',
      difficulty: 'Hard',
      type: 'code',
      prompt: 'Write `def sum_n(n)` returning sum 1..n (sanity check — use formula or loop).',
      starterCode: 'def sum_n(n):\n    pass',
      codeEvaluator: 'sum_natural',
      expectedOutput: '15',
    },
  ],
}

export const LEVELS = ['Easy', 'Medium', 'Hard']
